### ISSUE TITLE
Modal has fixed 400px width. please remove it.

### ISSUE THREAD

**Issue by arthurkhlghatyan** [kylefox/jquery-modal#142]

**Comment by kylefox** [comment]
The idea is that 400px is a reasonable default, rather than defaulting to 100% width.

It's possible to override the CSS and use whatever styles you wish:

```css
.modal {
  width: 75%;
}

.modal.narrow-modal {
  width: 200px;
}
```
