### ISSUE TITLE
disable blocker

### ISSUE THREAD

**Issue by tskkh** [kylefox/jquery-modal#148]
Hi, 
First of all thanks for sharing that plugin.

It is possible to disable the blocker? I don't need to overlay.
Please help.

**Comment by kylefox** [comment]
It's not an option built into the library, but you might be able to accomplish what you need using pure CSS.

If you simply want the block to be transparent, you can do so like this:

```css
.blocker {
  background-color: rgba(0,0,0,0);
}
```

However, the blocker will still be blocking the content on the page. So users will not be able to select text, etc. If you want the page to remain interactive, you should be able to do something like this:

```css
.blocker {
  visibility: hidden;
}

.modal {
  visibility: visible;
}
```

(Note: I haven't tested this code much so you might need to play around with it).

Hope this helps.
