### ISSUE TITLE
Change modal close icon 

### ISSUE THREAD

**Issue by sangsangg99** [kylefox/jquery-modal#230]
Hi ! How i can change modal close icon , i want to replace default icon and add a new close icon

**Comment by kylefox** [comment]
The close button is added with [normal CSS](https://github.com/kylefox/jquery-modal/blob/master/jquery.modal.css#L57). You can do something like:

```css
.modal a.close-modal {
  background-image: url('my-close-icon.png');
}
```

You can also adjust the width, height, and position of the close icon with CSS as well.
